name: ChatAs
version: 1.0.1
author: sl4v
description: Chat or a run a command as another player
website: sl4vkek.github.io
api-version: 1.14
main: me.sl4v.chatas.ChatAsMain
commands:
  chatas:
    description: Chat or run a command as another player on the server
    usage: /<command> [player name] [message or command]